"""Reusable utilities for a Strang linear algebra study track."""

from .applications import (
    affine_transform,
    correlation_matrix,
    covariance_matrix,
    fourier_series_fit,
    hill_cipher_decrypt,
    hill_cipher_encrypt,
    incidence_matrix,
    pagerank,
    solve_linear_program,
    weighted_least_squares,
)
from .numeric import (
    condition_number,
    dft_matrix,
    gauss_seidel,
    gram_schmidt,
    is_positive_definite,
    jacobi_method,
    least_squares,
    pca,
    power_iteration,
    project_onto_subspace,
    project_onto_vector,
    rank_k_svd,
)
from .symbolic import (
    cofactor_expansion,
    determinant_by_elimination,
    eigenpairs_symbolic,
    gaussian_elimination_steps,
    inverse_gauss_jordan,
    lu_factor,
    nullspace_basis,
    rref,
    to_sympy_matrix,
)

__all__ = [
    "affine_transform",
    "cofactor_expansion",
    "condition_number",
    "correlation_matrix",
    "covariance_matrix",
    "determinant_by_elimination",
    "dft_matrix",
    "eigenpairs_symbolic",
    "fourier_series_fit",
    "gauss_seidel",
    "gaussian_elimination_steps",
    "gram_schmidt",
    "hill_cipher_decrypt",
    "hill_cipher_encrypt",
    "incidence_matrix",
    "inverse_gauss_jordan",
    "is_positive_definite",
    "jacobi_method",
    "least_squares",
    "lu_factor",
    "nullspace_basis",
    "pagerank",
    "pca",
    "power_iteration",
    "project_onto_subspace",
    "project_onto_vector",
    "rank_k_svd",
    "rref",
    "solve_linear_program",
    "to_sympy_matrix",
    "weighted_least_squares",
]
